export const GET_BOOKING_PROCESS_ERROR = 'GET_BOOKING_PROCESS_ERROR';
export const GET_BOOKING_PROCESS_SUCCESS = 'GET_BOOKING_PROCESS_SUCCESS';
export const GET_BOOKING_PROCESS = 'GET_BOOKING_PROCESS';


export const CANCEL_BOOKING_PROCESS = 'CANCEL_BOOKING_PROCESS';
export const UPDATE_BOOKING_PROCESS_SUCCESS = 'UPDATE_BOOKING_PROCESS_SUCCESS';
export const UPDATE_BOOKING_PROCESS = 'UPDATE_BOOKING_PROCESS';


export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
